# Generated by Django 4.2.11 on 2024-05-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('lastname', models.CharField(default='', max_length=100)),
                ('birthday', models.DateField(null=True)),
                ('phone_number', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(default='', max_length=254)),
                ('short_description', models.TextField(default='')),
                ('profile_picture', models.URLField(default='')),
            ],
        ),
    ]
